version: "3"
services:
       app:
           container_name: node-app
           image: app
           build: .
           ports:
             - "4200:80"
       api:
           container_name: node-api
           image: api
           restart: always
           build: .
           ports:
             - "8000:8000"
           links:
             - mongo
       mongo:
             container_name: mongo1
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'